/* Full supplied drawings are preserved. This selection can be replaced later. */
window.BRAIN_PUZZLES = [
 {id:'scale',title:'Масштаб',image:'./assets/scale.png',tag:'ПЕРВЫЙ ШАГ',alt:'Зелёный квадрат равен 70. Прямоугольник той же высоты, вдвое меньшей ширины: неизвестное значение.',answers:['35'],hint:'Сравни площади фигур: высота одинакова, а ширина изменилась.',solution:'Прямоугольник вдвое уже квадрата при той же высоте. Его площадь — половина: 70 ÷ 2 = 35.'},
 {id:'cube',title:'Грани',image:'./assets/cube.webp',tag:'ПОСМОТРИ ИНАЧЕ',alt:'На квадрате написано 5, затем знак плюс, куб с числом 5 и знак вопроса.',answers:['150'],hint:'Фигуры тоже часть условия. Попробуй прочитать «пять в квадрате» и «пять в кубе».',solution:'5 в квадрате + 5 в кубе = 25 + 125 = 150.'},
 {id:'circle',title:'Круг',image:'./assets/circle.png',tag:'НАЙДИ ЗАКОНОМЕРНОСТЬ',alt:'На окружности сверху отмечен 0, справа — 14. Неизвестное значение расположено на отметке между нижней и левой точками.',answers:['35'],hint:'От 0 до 14 пройдена четверть окружности. Продолжи тот же шаг по часовой стрелке.',solution:'Четверть оборота соответствует 14: полный оборот — 56. Нужная отметка находится на 5/8 оборота: 56 × 5/8 = 35.'},
 {id:'diameter',title:'Диаметр',image:'./assets/diameter.svg',tag:'ГЕОМЕТРИЯ',alt:'Круг с радиусом 13. Отрезок AB проходит через центр. Найдите AB.',answers:['26'],hint:'Присмотрись: AB проходит через центр круга. Как связаны радиус и диаметр?',solution:'AB — диаметр, то есть два радиуса. 13 × 2 = 26.'},
 {id:'sequence',title:'Ряд',image:'./assets/sequence.png',tag:'ВНИМАНИЕ К ДЕТАЛЯМ',alt:'Последовательность: 3. 1 4 1 и знак вопроса.',answers:['5'],hint:'Это начало известной математической константы. Точка после тройки — часть записи.',solution:'Это цифры числа π: 3,141592… Следующая цифра после 3,141 — 5.'}
];

window.BRAIN_PUZZLES_EN = [
 {title:'Scale',tag:'FIRST STEP',alt:'A green square is worth 70. A rectangle has the same height and half the width; its value is unknown.',hint:'Compare the areas: the height stays the same, but the width changes.',solution:'The rectangle is half as wide as the square and has the same height. Its area is half as large: 70 ÷ 2 = 35.'},
 {title:'Faces',tag:'LOOK AGAIN',alt:'A square marked 5, a plus sign, a cube marked 5 and a question mark.',hint:'The shapes are part of the puzzle. Try reading “five squared” and “five cubed”.',solution:'5 squared + 5 cubed = 25 + 125 = 150.'},
 {title:'Circle',tag:'FIND THE PATTERN',alt:'A circle marked 0 at the top and 14 on the right. The unknown value is between the bottom and left points.',hint:'From 0 to 14 is a quarter turn. Continue clockwise at the same rate.',solution:'A quarter turn is worth 14, so a full turn is worth 56. The missing mark is 5/8 of a turn from the top: 56 × 5/8 = 35.'},
 {title:'Diameter',tag:'GEOMETRY',alt:'A circle with a radius of 13. Segment AB passes through its centre. Find AB.',hint:'AB passes through the centre of the circle. How are the radius and diameter related?',solution:'AB is the diameter: twice the radius. 13 × 2 = 26.'},
 {title:'Sequence',tag:'NOTICE THE DETAILS',alt:'The sequence 3. 1 4 1 followed by a question mark.',hint:'This is the start of a familiar mathematical constant. The point after 3 is part of the number.',solution:'These are the digits of π: 3.141592… The next digit after 3.141 is 5.'}
];
